// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extensions.proto

package com.v2ray.core.common.protoext;

public interface FieldOptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.common.protoext.FieldOpt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string any_wants = 1;</code>
   * @return A list containing the anyWants.
   */
  java.util.List<java.lang.String>
      getAnyWantsList();
  /**
   * <code>repeated string any_wants = 1;</code>
   * @return The count of anyWants.
   */
  int getAnyWantsCount();
  /**
   * <code>repeated string any_wants = 1;</code>
   * @param index The index of the element to return.
   * @return The anyWants at the given index.
   */
  java.lang.String getAnyWants(int index);
  /**
   * <code>repeated string any_wants = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the anyWants at the given index.
   */
  com.google.protobuf.ByteString
      getAnyWantsBytes(int index);

  /**
   * <code>repeated string allowed_values = 2;</code>
   * @return A list containing the allowedValues.
   */
  java.util.List<java.lang.String>
      getAllowedValuesList();
  /**
   * <code>repeated string allowed_values = 2;</code>
   * @return The count of allowedValues.
   */
  int getAllowedValuesCount();
  /**
   * <code>repeated string allowed_values = 2;</code>
   * @param index The index of the element to return.
   * @return The allowedValues at the given index.
   */
  java.lang.String getAllowedValues(int index);
  /**
   * <code>repeated string allowed_values = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedValues at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedValuesBytes(int index);

  /**
   * <code>repeated string allowed_value_types = 3;</code>
   * @return A list containing the allowedValueTypes.
   */
  java.util.List<java.lang.String>
      getAllowedValueTypesList();
  /**
   * <code>repeated string allowed_value_types = 3;</code>
   * @return The count of allowedValueTypes.
   */
  int getAllowedValueTypesCount();
  /**
   * <code>repeated string allowed_value_types = 3;</code>
   * @param index The index of the element to return.
   * @return The allowedValueTypes at the given index.
   */
  java.lang.String getAllowedValueTypes(int index);
  /**
   * <code>repeated string allowed_value_types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedValueTypes at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedValueTypesBytes(int index);

  /**
   * <pre>
   * convert_time_read_file_into read a file into another field, and clear this field during input parsing
   * </pre>
   *
   * <code>string convert_time_read_file_into = 4;</code>
   * @return The convertTimeReadFileInto.
   */
  java.lang.String getConvertTimeReadFileInto();
  /**
   * <pre>
   * convert_time_read_file_into read a file into another field, and clear this field during input parsing
   * </pre>
   *
   * <code>string convert_time_read_file_into = 4;</code>
   * @return The bytes for convertTimeReadFileInto.
   */
  com.google.protobuf.ByteString
      getConvertTimeReadFileIntoBytes();

  /**
   * <pre>
   * forbidden marks a boolean to be inaccessible to user
   * </pre>
   *
   * <code>bool forbidden = 5;</code>
   * @return The forbidden.
   */
  boolean getForbidden();

  /**
   * <pre>
   * convert_time_resource_loading read a file, and place its resource hash into another field
   * </pre>
   *
   * <code>string convert_time_resource_loading = 6;</code>
   * @return The convertTimeResourceLoading.
   */
  java.lang.String getConvertTimeResourceLoading();
  /**
   * <pre>
   * convert_time_resource_loading read a file, and place its resource hash into another field
   * </pre>
   *
   * <code>string convert_time_resource_loading = 6;</code>
   * @return The bytes for convertTimeResourceLoading.
   */
  com.google.protobuf.ByteString
      getConvertTimeResourceLoadingBytes();

  /**
   * <pre>
   * convert_time_parse_ip parse a string ip address, and put its binary representation into another field
   * </pre>
   *
   * <code>string convert_time_parse_ip = 7;</code>
   * @return The convertTimeParseIp.
   */
  java.lang.String getConvertTimeParseIp();
  /**
   * <pre>
   * convert_time_parse_ip parse a string ip address, and put its binary representation into another field
   * </pre>
   *
   * <code>string convert_time_parse_ip = 7;</code>
   * @return The bytes for convertTimeParseIp.
   */
  com.google.protobuf.ByteString
      getConvertTimeParseIpBytes();
}
