// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extensions.proto

package com.v2ray.core.common.protoext;

public interface MessageOptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.common.protoext.MessageOpt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string type = 1;</code>
   * @return A list containing the type.
   */
  java.util.List<java.lang.String>
      getTypeList();
  /**
   * <code>repeated string type = 1;</code>
   * @return The count of type.
   */
  int getTypeCount();
  /**
   * <code>repeated string type = 1;</code>
   * @param index The index of the element to return.
   * @return The type at the given index.
   */
  java.lang.String getType(int index);
  /**
   * <code>repeated string type = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the type at the given index.
   */
  com.google.protobuf.ByteString
      getTypeBytes(int index);

  /**
   * <code>repeated string short_name = 2;</code>
   * @return A list containing the shortName.
   */
  java.util.List<java.lang.String>
      getShortNameList();
  /**
   * <code>repeated string short_name = 2;</code>
   * @return The count of shortName.
   */
  int getShortNameCount();
  /**
   * <code>repeated string short_name = 2;</code>
   * @param index The index of the element to return.
   * @return The shortName at the given index.
   */
  java.lang.String getShortName(int index);
  /**
   * <code>repeated string short_name = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the shortName at the given index.
   */
  com.google.protobuf.ByteString
      getShortNameBytes(int index);

  /**
   * <code>string transport_original_name = 86001;</code>
   * @return The transportOriginalName.
   */
  java.lang.String getTransportOriginalName();
  /**
   * <code>string transport_original_name = 86001;</code>
   * @return The bytes for transportOriginalName.
   */
  com.google.protobuf.ByteString
      getTransportOriginalNameBytes();
}
