// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

/**
 * <pre>
 * IP for routing decision, in CIDR form.
 * </pre>
 *
 * Protobuf type {@code v2ray.core.app.router.routercommon.CIDR}
 */
public final class CIDR extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.router.routercommon.CIDR)
    CIDROrBuilder {
private static final long serialVersionUID = 0L;
  // Use CIDR.newBuilder() to construct.
  private CIDR(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CIDR() {
    ip_ = com.google.protobuf.ByteString.EMPTY;
    ipAddr_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CIDR();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_CIDR_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.router.routercommon.CIDR.class, com.v2ray.core.app.router.routercommon.CIDR.Builder.class);
  }

  public static final int IP_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString ip_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * IP address, should be either 4 or 16 bytes.
   * </pre>
   *
   * <code>bytes ip = 1;</code>
   * @return The ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIp() {
    return ip_;
  }

  public static final int PREFIX_FIELD_NUMBER = 2;
  private int prefix_ = 0;
  /**
   * <pre>
   * Number of leading ones in the network mask.
   * </pre>
   *
   * <code>uint32 prefix = 2;</code>
   * @return The prefix.
   */
  @java.lang.Override
  public int getPrefix() {
    return prefix_;
  }

  public static final int IP_ADDR_FIELD_NUMBER = 68000;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipAddr_ = "";
  /**
   * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The ipAddr.
   */
  @java.lang.Override
  public java.lang.String getIpAddr() {
    java.lang.Object ref = ipAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipAddr_ = s;
      return s;
    }
  }
  /**
   * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The bytes for ipAddr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpAddrBytes() {
    java.lang.Object ref = ipAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!ip_.isEmpty()) {
      output.writeBytes(1, ip_);
    }
    if (prefix_ != 0) {
      output.writeUInt32(2, prefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 68000, ipAddr_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!ip_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, ip_);
    }
    if (prefix_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, prefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(68000, ipAddr_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.router.routercommon.CIDR)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.router.routercommon.CIDR other = (com.v2ray.core.app.router.routercommon.CIDR) obj;

    if (!getIp()
        .equals(other.getIp())) return false;
    if (getPrefix()
        != other.getPrefix()) return false;
    if (!getIpAddr()
        .equals(other.getIpAddr())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getPrefix();
    hash = (37 * hash) + IP_ADDR_FIELD_NUMBER;
    hash = (53 * hash) + getIpAddr().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.CIDR parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.router.routercommon.CIDR prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * IP for routing decision, in CIDR form.
   * </pre>
   *
   * Protobuf type {@code v2ray.core.app.router.routercommon.CIDR}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.routercommon.CIDR)
      com.v2ray.core.app.router.routercommon.CIDROrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_CIDR_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.routercommon.CIDR.class, com.v2ray.core.app.router.routercommon.CIDR.Builder.class);
    }

    // Construct using com.v2ray.core.app.router.routercommon.CIDR.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ip_ = com.google.protobuf.ByteString.EMPTY;
      prefix_ = 0;
      ipAddr_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.CIDR getDefaultInstanceForType() {
      return com.v2ray.core.app.router.routercommon.CIDR.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.CIDR build() {
      com.v2ray.core.app.router.routercommon.CIDR result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.CIDR buildPartial() {
      com.v2ray.core.app.router.routercommon.CIDR result = new com.v2ray.core.app.router.routercommon.CIDR(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.v2ray.core.app.router.routercommon.CIDR result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ip_ = ip_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.prefix_ = prefix_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ipAddr_ = ipAddr_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.router.routercommon.CIDR) {
        return mergeFrom((com.v2ray.core.app.router.routercommon.CIDR)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.router.routercommon.CIDR other) {
      if (other == com.v2ray.core.app.router.routercommon.CIDR.getDefaultInstance()) return this;
      if (other.getIp() != com.google.protobuf.ByteString.EMPTY) {
        setIp(other.getIp());
      }
      if (other.getPrefix() != 0) {
        setPrefix(other.getPrefix());
      }
      if (!other.getIpAddr().isEmpty()) {
        ipAddr_ = other.ipAddr_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ip_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              prefix_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 544002: {
              ipAddr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 544002
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString ip_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * IP address, should be either 4 or 16 bytes.
     * </pre>
     *
     * <code>bytes ip = 1;</code>
     * @return The ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIp() {
      return ip_;
    }
    /**
     * <pre>
     * IP address, should be either 4 or 16 bytes.
     * </pre>
     *
     * <code>bytes ip = 1;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IP address, should be either 4 or 16 bytes.
     * </pre>
     *
     * <code>bytes ip = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }

    private int prefix_ ;
    /**
     * <pre>
     * Number of leading ones in the network mask.
     * </pre>
     *
     * <code>uint32 prefix = 2;</code>
     * @return The prefix.
     */
    @java.lang.Override
    public int getPrefix() {
      return prefix_;
    }
    /**
     * <pre>
     * Number of leading ones in the network mask.
     * </pre>
     *
     * <code>uint32 prefix = 2;</code>
     * @param value The prefix to set.
     * @return This builder for chaining.
     */
    public Builder setPrefix(int value) {
      
      prefix_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of leading ones in the network mask.
     * </pre>
     *
     * <code>uint32 prefix = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrefix() {
      bitField0_ = (bitField0_ & ~0x00000002);
      prefix_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ipAddr_ = "";
    /**
     * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return The ipAddr.
     */
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return The bytes for ipAddr.
     */
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @param value The ipAddr to set.
     * @return This builder for chaining.
     */
    public Builder setIpAddr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipAddr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearIpAddr() {
      ipAddr_ = getDefaultInstance().getIpAddr();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @param value The bytes for ipAddr to set.
     * @return This builder for chaining.
     */
    public Builder setIpAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipAddr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.routercommon.CIDR)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.router.routercommon.CIDR)
  private static final com.v2ray.core.app.router.routercommon.CIDR DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.router.routercommon.CIDR();
  }

  public static com.v2ray.core.app.router.routercommon.CIDR getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CIDR>
      PARSER = new com.google.protobuf.AbstractParser<CIDR>() {
    @java.lang.Override
    public CIDR parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CIDR> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CIDR> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.CIDR getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

