// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface CIDROrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.CIDR)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * IP address, should be either 4 or 16 bytes.
   * </pre>
   *
   * <code>bytes ip = 1;</code>
   * @return The ip.
   */
  com.google.protobuf.ByteString getIp();

  /**
   * <pre>
   * Number of leading ones in the network mask.
   * </pre>
   *
   * <code>uint32 prefix = 2;</code>
   * @return The prefix.
   */
  int getPrefix();

  /**
   * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The ipAddr.
   */
  java.lang.String getIpAddr();
  /**
   * <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The bytes for ipAddr.
   */
  com.google.protobuf.ByteString
      getIpAddrBytes();
}
