// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public final class Dat {
  private Dat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_Domain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_Domain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_CIDR_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_GeoIP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_GeoIPList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_GeoSite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_GeoSite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_router_routercommon_GeoSiteList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_router_routercommon_GeoSiteList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdat.proto\022\"v2ray.core.app.router.route" +
      "rcommon\032\020extensions.proto\"\253\002\n\006Domain\022=\n\004" +
      "type\030\001 \001(\0162/.v2ray.core.app.router.route" +
      "rcommon.Domain.Type\022\r\n\005value\030\002 \001(\t\022G\n\tat" +
      "tribute\030\003 \003(\01324.v2ray.core.app.router.ro" +
      "utercommon.Domain.Attribute\032R\n\tAttribute" +
      "\022\013\n\003key\030\001 \001(\t\022\024\n\nbool_value\030\002 \001(\010H\000\022\023\n\ti" +
      "nt_value\030\003 \001(\003H\000B\r\n\013typed_value\"6\n\004Type\022" +
      "\t\n\005Plain\020\000\022\t\n\005Regex\020\001\022\016\n\nRootDomain\020\002\022\010\n" +
      "\004Full\020\003\"?\n\004CIDR\022\n\n\002ip\030\001 \001(\014\022\016\n\006prefix\030\002 " +
      "\001(\r\022\033\n\007ip_addr\030\240\223\004 \001(\tB\010\202\265\030\004:\002ip\"\273\001\n\005Geo" +
      "IP\022\024\n\014country_code\030\001 \001(\t\0226\n\004cidr\030\002 \003(\0132(" +
      ".v2ray.core.app.router.routercommon.CIDR" +
      "\022\025\n\rinverse_match\030\003 \001(\010\022\025\n\rresource_hash" +
      "\030\004 \001(\014\022\014\n\004code\030\005 \001(\t\022(\n\tfile_path\030\240\223\004 \001(" +
      "\tB\023\202\265\030\0172\rresource_hash\"E\n\tGeoIPList\0228\n\005e" +
      "ntry\030\001 \003(\0132).v2ray.core.app.router.route" +
      "rcommon.GeoIP\"\252\001\n\007GeoSite\022\024\n\014country_cod" +
      "e\030\001 \001(\t\022:\n\006domain\030\002 \003(\0132*.v2ray.core.app" +
      ".router.routercommon.Domain\022\025\n\rresource_" +
      "hash\030\003 \001(\014\022\014\n\004code\030\004 \001(\t\022(\n\tfile_path\030\240\223" +
      "\004 \001(\tB\023\202\265\030\0172\rresource_hash\"I\n\013GeoSiteLis" +
      "t\022:\n\005entry\030\001 \003(\0132+.v2ray.core.app.router" +
      ".routercommon.GeoSiteB\207\001\n&com.v2ray.core" +
      ".app.router.routercommonP\001Z6github.com/v" +
      "2fly/v2ray-core/v5/app/router/routercomm" +
      "on\252\002\"V2Ray.Core.App.Router.Routercommonb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.v2ray.core.common.protoext.Extensions.getDescriptor(),
        });
    internal_static_v2ray_core_app_router_routercommon_Domain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_app_router_routercommon_Domain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_Domain_descriptor,
        new java.lang.String[] { "Type", "Value", "Attribute", });
    internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor =
      internal_static_v2ray_core_app_router_routercommon_Domain_descriptor.getNestedTypes().get(0);
    internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor,
        new java.lang.String[] { "Key", "BoolValue", "IntValue", "TypedValue", });
    internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v2ray_core_app_router_routercommon_CIDR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_CIDR_descriptor,
        new java.lang.String[] { "Ip", "Prefix", "IpAddr", });
    internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_v2ray_core_app_router_routercommon_GeoIP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor,
        new java.lang.String[] { "CountryCode", "Cidr", "InverseMatch", "ResourceHash", "Code", "FilePath", });
    internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_v2ray_core_app_router_routercommon_GeoIPList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_v2ray_core_app_router_routercommon_GeoSite_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_v2ray_core_app_router_routercommon_GeoSite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_GeoSite_descriptor,
        new java.lang.String[] { "CountryCode", "Domain", "ResourceHash", "Code", "FilePath", });
    internal_static_v2ray_core_app_router_routercommon_GeoSiteList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_v2ray_core_app_router_routercommon_GeoSiteList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_router_routercommon_GeoSiteList_descriptor,
        new java.lang.String[] { "Entry", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.v2ray.core.common.protoext.Extensions.fieldOpt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.v2ray.core.common.protoext.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
