// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

/**
 * <pre>
 * Domain for routing decision.
 * </pre>
 *
 * Protobuf type {@code v2ray.core.app.router.routercommon.Domain}
 */
public final class Domain extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.router.routercommon.Domain)
    DomainOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Domain.newBuilder() to construct.
  private Domain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Domain() {
    type_ = 0;
    value_ = "";
    attribute_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Domain();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.router.routercommon.Domain.class, com.v2ray.core.app.router.routercommon.Domain.Builder.class);
  }

  /**
   * <pre>
   * Type of domain value.
   * </pre>
   *
   * Protobuf enum {@code v2ray.core.app.router.routercommon.Domain.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The value is used as is.
     * </pre>
     *
     * <code>Plain = 0;</code>
     */
    Plain(0),
    /**
     * <pre>
     * The value is used as a regular expression.
     * </pre>
     *
     * <code>Regex = 1;</code>
     */
    Regex(1),
    /**
     * <pre>
     * The value is a root domain.
     * </pre>
     *
     * <code>RootDomain = 2;</code>
     */
    RootDomain(2),
    /**
     * <pre>
     * The value is a domain.
     * </pre>
     *
     * <code>Full = 3;</code>
     */
    Full(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The value is used as is.
     * </pre>
     *
     * <code>Plain = 0;</code>
     */
    public static final int Plain_VALUE = 0;
    /**
     * <pre>
     * The value is used as a regular expression.
     * </pre>
     *
     * <code>Regex = 1;</code>
     */
    public static final int Regex_VALUE = 1;
    /**
     * <pre>
     * The value is a root domain.
     * </pre>
     *
     * <code>RootDomain = 2;</code>
     */
    public static final int RootDomain_VALUE = 2;
    /**
     * <pre>
     * The value is a domain.
     * </pre>
     *
     * <code>Full = 3;</code>
     */
    public static final int Full_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Plain;
        case 1: return Regex;
        case 2: return RootDomain;
        case 3: return Full;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Domain.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v2ray.core.app.router.routercommon.Domain.Type)
  }

  public interface AttributeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.Domain.Attribute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bool bool_value = 2;</code>
     * @return Whether the boolValue field is set.
     */
    boolean hasBoolValue();
    /**
     * <code>bool bool_value = 2;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>int64 int_value = 3;</code>
     * @return Whether the intValue field is set.
     */
    boolean hasIntValue();
    /**
     * <code>int64 int_value = 3;</code>
     * @return The intValue.
     */
    long getIntValue();

    public com.v2ray.core.app.router.routercommon.Domain.Attribute.TypedValueCase getTypedValueCase();
  }
  /**
   * Protobuf type {@code v2ray.core.app.router.routercommon.Domain.Attribute}
   */
  public static final class Attribute extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.app.router.routercommon.Domain.Attribute)
      AttributeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Attribute.newBuilder() to construct.
    private Attribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Attribute() {
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Attribute();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.routercommon.Domain.Attribute.class, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder.class);
    }

    private int typedValueCase_ = 0;
    private java.lang.Object typedValue_;
    public enum TypedValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BOOL_VALUE(2),
      INT_VALUE(3),
      TYPEDVALUE_NOT_SET(0);
      private final int value;
      private TypedValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypedValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypedValueCase forNumber(int value) {
        switch (value) {
          case 2: return BOOL_VALUE;
          case 3: return INT_VALUE;
          case 0: return TYPEDVALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypedValueCase
    getTypedValueCase() {
      return TypedValueCase.forNumber(
          typedValueCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 2;
    /**
     * <code>bool bool_value = 2;</code>
     * @return Whether the boolValue field is set.
     */
    @java.lang.Override
    public boolean hasBoolValue() {
      return typedValueCase_ == 2;
    }
    /**
     * <code>bool bool_value = 2;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      if (typedValueCase_ == 2) {
        return (java.lang.Boolean) typedValue_;
      }
      return false;
    }

    public static final int INT_VALUE_FIELD_NUMBER = 3;
    /**
     * <code>int64 int_value = 3;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return typedValueCase_ == 3;
    }
    /**
     * <code>int64 int_value = 3;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public long getIntValue() {
      if (typedValueCase_ == 3) {
        return (java.lang.Long) typedValue_;
      }
      return 0L;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (typedValueCase_ == 2) {
        output.writeBool(
            2, (boolean)((java.lang.Boolean) typedValue_));
      }
      if (typedValueCase_ == 3) {
        output.writeInt64(
            3, (long)((java.lang.Long) typedValue_));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (typedValueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              2, (boolean)((java.lang.Boolean) typedValue_));
      }
      if (typedValueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(
              3, (long)((java.lang.Long) typedValue_));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.app.router.routercommon.Domain.Attribute)) {
        return super.equals(obj);
      }
      com.v2ray.core.app.router.routercommon.Domain.Attribute other = (com.v2ray.core.app.router.routercommon.Domain.Attribute) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getTypedValueCase().equals(other.getTypedValueCase())) return false;
      switch (typedValueCase_) {
        case 2:
          if (getBoolValue()
              != other.getBoolValue()) return false;
          break;
        case 3:
          if (getIntValue()
              != other.getIntValue()) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      switch (typedValueCase_) {
        case 2:
          hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolValue());
          break;
        case 3:
          hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getIntValue());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.app.router.routercommon.Domain.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.app.router.routercommon.Domain.Attribute prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.app.router.routercommon.Domain.Attribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.routercommon.Domain.Attribute)
        com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.app.router.routercommon.Domain.Attribute.class, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder.class);
      }

      // Construct using com.v2ray.core.app.router.routercommon.Domain.Attribute.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        typedValueCase_ = 0;
        typedValue_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_Attribute_descriptor;
      }

      @java.lang.Override
      public com.v2ray.core.app.router.routercommon.Domain.Attribute getDefaultInstanceForType() {
        return com.v2ray.core.app.router.routercommon.Domain.Attribute.getDefaultInstance();
      }

      @java.lang.Override
      public com.v2ray.core.app.router.routercommon.Domain.Attribute build() {
        com.v2ray.core.app.router.routercommon.Domain.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.v2ray.core.app.router.routercommon.Domain.Attribute buildPartial() {
        com.v2ray.core.app.router.routercommon.Domain.Attribute result = new com.v2ray.core.app.router.routercommon.Domain.Attribute(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.v2ray.core.app.router.routercommon.Domain.Attribute result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
      }

      private void buildPartialOneofs(com.v2ray.core.app.router.routercommon.Domain.Attribute result) {
        result.typedValueCase_ = typedValueCase_;
        result.typedValue_ = this.typedValue_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.app.router.routercommon.Domain.Attribute) {
          return mergeFrom((com.v2ray.core.app.router.routercommon.Domain.Attribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.app.router.routercommon.Domain.Attribute other) {
        if (other == com.v2ray.core.app.router.routercommon.Domain.Attribute.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        switch (other.getTypedValueCase()) {
          case BOOL_VALUE: {
            setBoolValue(other.getBoolValue());
            break;
          }
          case INT_VALUE: {
            setIntValue(other.getIntValue());
            break;
          }
          case TYPEDVALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                typedValue_ = input.readBool();
                typedValueCase_ = 2;
                break;
              } // case 16
              case 24: {
                typedValue_ = input.readInt64();
                typedValueCase_ = 3;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int typedValueCase_ = 0;
      private java.lang.Object typedValue_;
      public TypedValueCase
          getTypedValueCase() {
        return TypedValueCase.forNumber(
            typedValueCase_);
      }

      public Builder clearTypedValue() {
        typedValueCase_ = 0;
        typedValue_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>bool bool_value = 2;</code>
       * @return Whether the boolValue field is set.
       */
      public boolean hasBoolValue() {
        return typedValueCase_ == 2;
      }
      /**
       * <code>bool bool_value = 2;</code>
       * @return The boolValue.
       */
      public boolean getBoolValue() {
        if (typedValueCase_ == 2) {
          return (java.lang.Boolean) typedValue_;
        }
        return false;
      }
      /**
       * <code>bool bool_value = 2;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {
        
        typedValueCase_ = 2;
        typedValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        if (typedValueCase_ == 2) {
          typedValueCase_ = 0;
          typedValue_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>int64 int_value = 3;</code>
       * @return Whether the intValue field is set.
       */
      public boolean hasIntValue() {
        return typedValueCase_ == 3;
      }
      /**
       * <code>int64 int_value = 3;</code>
       * @return The intValue.
       */
      public long getIntValue() {
        if (typedValueCase_ == 3) {
          return (java.lang.Long) typedValue_;
        }
        return 0L;
      }
      /**
       * <code>int64 int_value = 3;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(long value) {
        
        typedValueCase_ = 3;
        typedValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        if (typedValueCase_ == 3) {
          typedValueCase_ = 0;
          typedValue_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.routercommon.Domain.Attribute)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.app.router.routercommon.Domain.Attribute)
    private static final com.v2ray.core.app.router.routercommon.Domain.Attribute DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.app.router.routercommon.Domain.Attribute();
    }

    public static com.v2ray.core.app.router.routercommon.Domain.Attribute getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Attribute>
        PARSER = new com.google.protobuf.AbstractParser<Attribute>() {
      @java.lang.Override
      public Attribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Attribute> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Attribute> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.Domain.Attribute getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.v2ray.core.app.router.routercommon.Domain.Type getType() {
    com.v2ray.core.app.router.routercommon.Domain.Type result = com.v2ray.core.app.router.routercommon.Domain.Type.forNumber(type_);
    return result == null ? com.v2ray.core.app.router.routercommon.Domain.Type.UNRECOGNIZED : result;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object value_ = "";
  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute> attribute_;
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute> getAttributeList() {
    return attribute_;
  }
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder> 
      getAttributeOrBuilderList() {
    return attribute_;
  }
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  @java.lang.Override
  public int getAttributeCount() {
    return attribute_.size();
  }
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.Domain.Attribute getAttribute(int index) {
    return attribute_.get(index);
  }
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder getAttributeOrBuilder(
      int index) {
    return attribute_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.v2ray.core.app.router.routercommon.Domain.Type.Plain.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    for (int i = 0; i < attribute_.size(); i++) {
      output.writeMessage(3, attribute_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.v2ray.core.app.router.routercommon.Domain.Type.Plain.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    for (int i = 0; i < attribute_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, attribute_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.router.routercommon.Domain)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.router.routercommon.Domain other = (com.v2ray.core.app.router.routercommon.Domain) obj;

    if (type_ != other.type_) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getAttributeList()
        .equals(other.getAttributeList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    if (getAttributeCount() > 0) {
      hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.Domain parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.router.routercommon.Domain prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Domain for routing decision.
   * </pre>
   *
   * Protobuf type {@code v2ray.core.app.router.routercommon.Domain}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.routercommon.Domain)
      com.v2ray.core.app.router.routercommon.DomainOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.routercommon.Domain.class, com.v2ray.core.app.router.routercommon.Domain.Builder.class);
    }

    // Construct using com.v2ray.core.app.router.routercommon.Domain.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      value_ = "";
      if (attributeBuilder_ == null) {
        attribute_ = java.util.Collections.emptyList();
      } else {
        attribute_ = null;
        attributeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_Domain_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.Domain getDefaultInstanceForType() {
      return com.v2ray.core.app.router.routercommon.Domain.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.Domain build() {
      com.v2ray.core.app.router.routercommon.Domain result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.Domain buildPartial() {
      com.v2ray.core.app.router.routercommon.Domain result = new com.v2ray.core.app.router.routercommon.Domain(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.v2ray.core.app.router.routercommon.Domain result) {
      if (attributeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          attribute_ = java.util.Collections.unmodifiableList(attribute_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.attribute_ = attribute_;
      } else {
        result.attribute_ = attributeBuilder_.build();
      }
    }

    private void buildPartial0(com.v2ray.core.app.router.routercommon.Domain result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.router.routercommon.Domain) {
        return mergeFrom((com.v2ray.core.app.router.routercommon.Domain)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.router.routercommon.Domain other) {
      if (other == com.v2ray.core.app.router.routercommon.Domain.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (attributeBuilder_ == null) {
        if (!other.attribute_.isEmpty()) {
          if (attribute_.isEmpty()) {
            attribute_ = other.attribute_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAttributeIsMutable();
            attribute_.addAll(other.attribute_);
          }
          onChanged();
        }
      } else {
        if (!other.attribute_.isEmpty()) {
          if (attributeBuilder_.isEmpty()) {
            attributeBuilder_.dispose();
            attributeBuilder_ = null;
            attribute_ = other.attribute_;
            bitField0_ = (bitField0_ & ~0x00000004);
            attributeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributeFieldBuilder() : null;
          } else {
            attributeBuilder_.addAllMessages(other.attribute_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              value_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.v2ray.core.app.router.routercommon.Domain.Attribute m =
                  input.readMessage(
                      com.v2ray.core.app.router.routercommon.Domain.Attribute.parser(),
                      extensionRegistry);
              if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                attribute_.add(m);
              } else {
                attributeBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Domain matching type.
     * </pre>
     *
     * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Domain matching type.
     * </pre>
     *
     * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain matching type.
     * </pre>
     *
     * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.Domain.Type getType() {
      com.v2ray.core.app.router.routercommon.Domain.Type result = com.v2ray.core.app.router.routercommon.Domain.Type.forNumber(type_);
      return result == null ? com.v2ray.core.app.router.routercommon.Domain.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Domain matching type.
     * </pre>
     *
     * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.v2ray.core.app.router.routercommon.Domain.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain matching type.
     * </pre>
     *
     * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <pre>
     * Domain value.
     * </pre>
     *
     * <code>string value = 2;</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Domain value.
     * </pre>
     *
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Domain value.
     * </pre>
     *
     * <code>string value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain value.
     * </pre>
     *
     * <code>string value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      value_ = getDefaultInstance().getValue();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain value.
     * </pre>
     *
     * <code>string value = 2;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute> attribute_ =
      java.util.Collections.emptyList();
    private void ensureAttributeIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        attribute_ = new java.util.ArrayList<com.v2ray.core.app.router.routercommon.Domain.Attribute>(attribute_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.Domain.Attribute, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder, com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder> attributeBuilder_;

    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute> getAttributeList() {
      if (attributeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attribute_);
      } else {
        return attributeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public int getAttributeCount() {
      if (attributeBuilder_ == null) {
        return attribute_.size();
      } else {
        return attributeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public com.v2ray.core.app.router.routercommon.Domain.Attribute getAttribute(int index) {
      if (attributeBuilder_ == null) {
        return attribute_.get(index);
      } else {
        return attributeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder setAttribute(
        int index, com.v2ray.core.app.router.routercommon.Domain.Attribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.set(index, value);
        onChanged();
      } else {
        attributeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder setAttribute(
        int index, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder addAttribute(com.v2ray.core.app.router.routercommon.Domain.Attribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.add(value);
        onChanged();
      } else {
        attributeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder addAttribute(
        int index, com.v2ray.core.app.router.routercommon.Domain.Attribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.add(index, value);
        onChanged();
      } else {
        attributeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder addAttribute(
        com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.add(builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder addAttribute(
        int index, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder addAllAttribute(
        java.lang.Iterable<? extends com.v2ray.core.app.router.routercommon.Domain.Attribute> values) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attribute_);
        onChanged();
      } else {
        attributeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder clearAttribute() {
      if (attributeBuilder_ == null) {
        attribute_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        attributeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public Builder removeAttribute(int index) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.remove(index);
        onChanged();
      } else {
        attributeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder getAttributeBuilder(
        int index) {
      return getAttributeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder getAttributeOrBuilder(
        int index) {
      if (attributeBuilder_ == null) {
        return attribute_.get(index);  } else {
        return attributeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public java.util.List<? extends com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder> 
         getAttributeOrBuilderList() {
      if (attributeBuilder_ != null) {
        return attributeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attribute_);
      }
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder addAttributeBuilder() {
      return getAttributeFieldBuilder().addBuilder(
          com.v2ray.core.app.router.routercommon.Domain.Attribute.getDefaultInstance());
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder addAttributeBuilder(
        int index) {
      return getAttributeFieldBuilder().addBuilder(
          index, com.v2ray.core.app.router.routercommon.Domain.Attribute.getDefaultInstance());
    }
    /**
     * <pre>
     * Attributes of this domain. May be used for filtering.
     * </pre>
     *
     * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder> 
         getAttributeBuilderList() {
      return getAttributeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.Domain.Attribute, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder, com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder> 
        getAttributeFieldBuilder() {
      if (attributeBuilder_ == null) {
        attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.v2ray.core.app.router.routercommon.Domain.Attribute, com.v2ray.core.app.router.routercommon.Domain.Attribute.Builder, com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder>(
                attribute_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        attribute_ = null;
      }
      return attributeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.routercommon.Domain)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.router.routercommon.Domain)
  private static final com.v2ray.core.app.router.routercommon.Domain DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.router.routercommon.Domain();
  }

  public static com.v2ray.core.app.router.routercommon.Domain getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Domain>
      PARSER = new com.google.protobuf.AbstractParser<Domain>() {
    @java.lang.Override
    public Domain parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Domain> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Domain> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.Domain getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

