// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface DomainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.Domain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.v2ray.core.app.router.routercommon.Domain.Type type = 1;</code>
   * @return The type.
   */
  com.v2ray.core.app.router.routercommon.Domain.Type getType();

  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  java.util.List<com.v2ray.core.app.router.routercommon.Domain.Attribute> 
      getAttributeList();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  com.v2ray.core.app.router.routercommon.Domain.Attribute getAttribute(int index);
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  int getAttributeCount();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  java.util.List<? extends com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder> 
      getAttributeOrBuilderList();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .v2ray.core.app.router.routercommon.Domain.Attribute attribute = 3;</code>
   */
  com.v2ray.core.app.router.routercommon.Domain.AttributeOrBuilder getAttributeOrBuilder(
      int index);
}
