// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface GeoIPListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.GeoIPList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  java.util.List<com.v2ray.core.app.router.routercommon.GeoIP> 
      getEntryList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  com.v2ray.core.app.router.routercommon.GeoIP getEntry(int index);
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  java.util.List<? extends com.v2ray.core.app.router.routercommon.GeoIPOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  com.v2ray.core.app.router.routercommon.GeoIPOrBuilder getEntryOrBuilder(
      int index);
}
