// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface GeoIPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.GeoIP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  java.util.List<com.v2ray.core.app.router.routercommon.CIDR> 
      getCidrList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  com.v2ray.core.app.router.routercommon.CIDR getCidr(int index);
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  int getCidrCount();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  java.util.List<? extends com.v2ray.core.app.router.routercommon.CIDROrBuilder> 
      getCidrOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  com.v2ray.core.app.router.routercommon.CIDROrBuilder getCidrOrBuilder(
      int index);

  /**
   * <code>bool inverse_match = 3;</code>
   * @return The inverseMatch.
   */
  boolean getInverseMatch();

  /**
   * <pre>
   * resource_hash instruct simplified config converter to load domain from geo file.
   * </pre>
   *
   * <code>bytes resource_hash = 4;</code>
   * @return The resourceHash.
   */
  com.google.protobuf.ByteString getResourceHash();

  /**
   * <code>string code = 5;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 5;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
