// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

/**
 * Protobuf type {@code v2ray.core.app.router.routercommon.GeoIPList}
 */
@SuppressWarnings("unchecked")
public final class GeoIPList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.router.routercommon.GeoIPList)
    GeoIPListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoIPList.newBuilder() to construct.
  private GeoIPList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoIPList() {
    entry_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoIPList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIPList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.router.routercommon.GeoIPList.class, com.v2ray.core.app.router.routercommon.GeoIPList.Builder.class);
  }

  public static final int ENTRY_FIELD_NUMBER = 1;
  private java.util.List<com.v2ray.core.app.router.routercommon.GeoIP> entry_;
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.app.router.routercommon.GeoIP> getEntryList() {
    return entry_;
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.v2ray.core.app.router.routercommon.GeoIPOrBuilder> 
      getEntryOrBuilderList() {
    return entry_;
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  @java.lang.Override
  public int getEntryCount() {
    return entry_.size();
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.GeoIP getEntry(int index) {
    return entry_.get(index);
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.GeoIPOrBuilder getEntryOrBuilder(
      int index) {
    return entry_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entry_.size(); i++) {
      output.writeMessage(1, entry_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entry_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entry_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.router.routercommon.GeoIPList)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.router.routercommon.GeoIPList other = (com.v2ray.core.app.router.routercommon.GeoIPList) obj;

    if (!getEntryList()
        .equals(other.getEntryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntryCount() > 0) {
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getEntryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIPList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.router.routercommon.GeoIPList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.app.router.routercommon.GeoIPList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.routercommon.GeoIPList)
      com.v2ray.core.app.router.routercommon.GeoIPListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIPList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.routercommon.GeoIPList.class, com.v2ray.core.app.router.routercommon.GeoIPList.Builder.class);
    }

    // Construct using com.v2ray.core.app.router.routercommon.GeoIPList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
      } else {
        entry_ = null;
        entryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIPList_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIPList getDefaultInstanceForType() {
      return com.v2ray.core.app.router.routercommon.GeoIPList.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIPList build() {
      com.v2ray.core.app.router.routercommon.GeoIPList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIPList buildPartial() {
      com.v2ray.core.app.router.routercommon.GeoIPList result = new com.v2ray.core.app.router.routercommon.GeoIPList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.v2ray.core.app.router.routercommon.GeoIPList result) {
      if (entryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entry_ = entry_;
      } else {
        result.entry_ = entryBuilder_.build();
      }
    }

    private void buildPartial0(com.v2ray.core.app.router.routercommon.GeoIPList result) {
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.router.routercommon.GeoIPList) {
        return mergeFrom((com.v2ray.core.app.router.routercommon.GeoIPList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.router.routercommon.GeoIPList other) {
      if (other == com.v2ray.core.app.router.routercommon.GeoIPList.getDefaultInstance()) return this;
      if (entryBuilder_ == null) {
        if (!other.entry_.isEmpty()) {
          if (entry_.isEmpty()) {
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntryIsMutable();
            entry_.addAll(other.entry_);
          }
          onChanged();
        }
      } else {
        if (!other.entry_.isEmpty()) {
          if (entryBuilder_.isEmpty()) {
            entryBuilder_.dispose();
            entryBuilder_ = null;
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntryFieldBuilder() : null;
          } else {
            entryBuilder_.addAllMessages(other.entry_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.v2ray.core.app.router.routercommon.GeoIP m =
                  input.readMessage(
                      com.v2ray.core.app.router.routercommon.GeoIP.parser(),
                      extensionRegistry);
              if (entryBuilder_ == null) {
                ensureEntryIsMutable();
                entry_.add(m);
              } else {
                entryBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.v2ray.core.app.router.routercommon.GeoIP> entry_ =
      java.util.Collections.emptyList();
    private void ensureEntryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entry_ = new java.util.ArrayList<com.v2ray.core.app.router.routercommon.GeoIP>(entry_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.GeoIP, com.v2ray.core.app.router.routercommon.GeoIP.Builder, com.v2ray.core.app.router.routercommon.GeoIPOrBuilder> entryBuilder_;

    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.GeoIP> getEntryList() {
      if (entryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entry_);
      } else {
        return entryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public int getEntryCount() {
      if (entryBuilder_ == null) {
        return entry_.size();
      } else {
        return entryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public com.v2ray.core.app.router.routercommon.GeoIP getEntry(int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);
      } else {
        return entryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder setEntry(
        int index, com.v2ray.core.app.router.routercommon.GeoIP value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.set(index, value);
        onChanged();
      } else {
        entryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder setEntry(
        int index, com.v2ray.core.app.router.routercommon.GeoIP.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.set(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder addEntry(com.v2ray.core.app.router.routercommon.GeoIP value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(value);
        onChanged();
      } else {
        entryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder addEntry(
        int index, com.v2ray.core.app.router.routercommon.GeoIP value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(index, value);
        onChanged();
      } else {
        entryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder addEntry(
        com.v2ray.core.app.router.routercommon.GeoIP.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder addEntry(
        int index, com.v2ray.core.app.router.routercommon.GeoIP.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder addAllEntry(
        java.lang.Iterable<? extends com.v2ray.core.app.router.routercommon.GeoIP> values) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entry_);
        onChanged();
      } else {
        entryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder clearEntry() {
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public Builder removeEntry(int index) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.remove(index);
        onChanged();
      } else {
        entryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public com.v2ray.core.app.router.routercommon.GeoIP.Builder getEntryBuilder(
        int index) {
      return getEntryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public com.v2ray.core.app.router.routercommon.GeoIPOrBuilder getEntryOrBuilder(
        int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);  } else {
        return entryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public java.util.List<? extends com.v2ray.core.app.router.routercommon.GeoIPOrBuilder> 
         getEntryOrBuilderList() {
      if (entryBuilder_ != null) {
        return entryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entry_);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public com.v2ray.core.app.router.routercommon.GeoIP.Builder addEntryBuilder() {
      return getEntryFieldBuilder().addBuilder(
          com.v2ray.core.app.router.routercommon.GeoIP.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public com.v2ray.core.app.router.routercommon.GeoIP.Builder addEntryBuilder(
        int index) {
      return getEntryFieldBuilder().addBuilder(
          index, com.v2ray.core.app.router.routercommon.GeoIP.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.GeoIP.Builder> 
         getEntryBuilderList() {
      return getEntryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.GeoIP, com.v2ray.core.app.router.routercommon.GeoIP.Builder, com.v2ray.core.app.router.routercommon.GeoIPOrBuilder> 
        getEntryFieldBuilder() {
      if (entryBuilder_ == null) {
        entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.v2ray.core.app.router.routercommon.GeoIP, com.v2ray.core.app.router.routercommon.GeoIP.Builder, com.v2ray.core.app.router.routercommon.GeoIPOrBuilder>(
                entry_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entry_ = null;
      }
      return entryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.routercommon.GeoIPList)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.router.routercommon.GeoIPList)
  private static final com.v2ray.core.app.router.routercommon.GeoIPList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.router.routercommon.GeoIPList();
  }

  public static com.v2ray.core.app.router.routercommon.GeoIPList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoIPList>
      PARSER = new com.google.protobuf.AbstractParser<GeoIPList>() {
    @java.lang.Override
    public GeoIPList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GeoIPList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoIPList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.GeoIPList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

