// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

/**
 * Protobuf type {@code v2ray.core.app.router.routercommon.GeoIP}
 */
@SuppressWarnings("unchecked")
public final class GeoIP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.router.routercommon.GeoIP)
    GeoIPOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoIP.newBuilder() to construct.
  private GeoIP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoIP() {
    countryCode_ = "";
    cidr_ = java.util.Collections.emptyList();
    resourceHash_ = com.google.protobuf.ByteString.EMPTY;
    code_ = "";
    filePath_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoIP();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.router.routercommon.GeoIP.class, com.v2ray.core.app.router.routercommon.GeoIP.Builder.class);
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object countryCode_ = "";
  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  @java.lang.Override
  public java.lang.String getCountryCode() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CIDR_FIELD_NUMBER = 2;
  private java.util.List<com.v2ray.core.app.router.routercommon.CIDR> cidr_;
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.app.router.routercommon.CIDR> getCidrList() {
    return cidr_;
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.v2ray.core.app.router.routercommon.CIDROrBuilder> 
      getCidrOrBuilderList() {
    return cidr_;
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  @java.lang.Override
  public int getCidrCount() {
    return cidr_.size();
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.CIDR getCidr(int index) {
    return cidr_.get(index);
  }
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
   */
  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.CIDROrBuilder getCidrOrBuilder(
      int index) {
    return cidr_.get(index);
  }

  public static final int INVERSE_MATCH_FIELD_NUMBER = 3;
  private boolean inverseMatch_ = false;
  /**
   * <code>bool inverse_match = 3;</code>
   * @return The inverseMatch.
   */
  @java.lang.Override
  public boolean getInverseMatch() {
    return inverseMatch_;
  }

  public static final int RESOURCE_HASH_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString resourceHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * resource_hash instruct simplified config converter to load domain from geo file.
   * </pre>
   *
   * <code>bytes resource_hash = 4;</code>
   * @return The resourceHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResourceHash() {
    return resourceHash_;
  }

  public static final int CODE_FIELD_NUMBER = 5;
  private volatile java.lang.Object code_ = "";
  /**
   * <code>string code = 5;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 5;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_PATH_FIELD_NUMBER = 68000;
  private volatile java.lang.Object filePath_ = "";
  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The filePath.
   */
  @java.lang.Override
  public java.lang.String getFilePath() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePath_ = s;
      return s;
    }
  }
  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The bytes for filePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, countryCode_);
    }
    for (int i = 0; i < cidr_.size(); i++) {
      output.writeMessage(2, cidr_.get(i));
    }
    if (inverseMatch_ != false) {
      output.writeBool(3, inverseMatch_);
    }
    if (!resourceHash_.isEmpty()) {
      output.writeBytes(4, resourceHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filePath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 68000, filePath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, countryCode_);
    }
    for (int i = 0; i < cidr_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, cidr_.get(i));
    }
    if (inverseMatch_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, inverseMatch_);
    }
    if (!resourceHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, resourceHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filePath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(68000, filePath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.router.routercommon.GeoIP)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.router.routercommon.GeoIP other = (com.v2ray.core.app.router.routercommon.GeoIP) obj;

    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (!getCidrList()
        .equals(other.getCidrList())) return false;
    if (getInverseMatch()
        != other.getInverseMatch()) return false;
    if (!getResourceHash()
        .equals(other.getResourceHash())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getFilePath()
        .equals(other.getFilePath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    if (getCidrCount() > 0) {
      hash = (37 * hash) + CIDR_FIELD_NUMBER;
      hash = (53 * hash) + getCidrList().hashCode();
    }
    hash = (37 * hash) + INVERSE_MATCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInverseMatch());
    hash = (37 * hash) + RESOURCE_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getResourceHash().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFilePath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.routercommon.GeoIP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.router.routercommon.GeoIP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.app.router.routercommon.GeoIP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.routercommon.GeoIP)
      com.v2ray.core.app.router.routercommon.GeoIPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.routercommon.GeoIP.class, com.v2ray.core.app.router.routercommon.GeoIP.Builder.class);
    }

    // Construct using com.v2ray.core.app.router.routercommon.GeoIP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      countryCode_ = "";
      if (cidrBuilder_ == null) {
        cidr_ = java.util.Collections.emptyList();
      } else {
        cidr_ = null;
        cidrBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      inverseMatch_ = false;
      resourceHash_ = com.google.protobuf.ByteString.EMPTY;
      code_ = "";
      filePath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.router.routercommon.Dat.internal_static_v2ray_core_app_router_routercommon_GeoIP_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIP getDefaultInstanceForType() {
      return com.v2ray.core.app.router.routercommon.GeoIP.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIP build() {
      com.v2ray.core.app.router.routercommon.GeoIP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.routercommon.GeoIP buildPartial() {
      com.v2ray.core.app.router.routercommon.GeoIP result = new com.v2ray.core.app.router.routercommon.GeoIP(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.v2ray.core.app.router.routercommon.GeoIP result) {
      if (cidrBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          cidr_ = java.util.Collections.unmodifiableList(cidr_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.cidr_ = cidr_;
      } else {
        result.cidr_ = cidrBuilder_.build();
      }
    }

    private void buildPartial0(com.v2ray.core.app.router.routercommon.GeoIP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.countryCode_ = countryCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inverseMatch_ = inverseMatch_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resourceHash_ = resourceHash_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.filePath_ = filePath_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.router.routercommon.GeoIP) {
        return mergeFrom((com.v2ray.core.app.router.routercommon.GeoIP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.router.routercommon.GeoIP other) {
      if (other == com.v2ray.core.app.router.routercommon.GeoIP.getDefaultInstance()) return this;
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (cidrBuilder_ == null) {
        if (!other.cidr_.isEmpty()) {
          if (cidr_.isEmpty()) {
            cidr_ = other.cidr_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCidrIsMutable();
            cidr_.addAll(other.cidr_);
          }
          onChanged();
        }
      } else {
        if (!other.cidr_.isEmpty()) {
          if (cidrBuilder_.isEmpty()) {
            cidrBuilder_.dispose();
            cidrBuilder_ = null;
            cidr_ = other.cidr_;
            bitField0_ = (bitField0_ & ~0x00000002);
            cidrBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCidrFieldBuilder() : null;
          } else {
            cidrBuilder_.addAllMessages(other.cidr_);
          }
        }
      }
      if (other.getInverseMatch() != false) {
        setInverseMatch(other.getInverseMatch());
      }
      if (other.getResourceHash() != com.google.protobuf.ByteString.EMPTY) {
        setResourceHash(other.getResourceHash());
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getFilePath().isEmpty()) {
        filePath_ = other.filePath_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              countryCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.v2ray.core.app.router.routercommon.CIDR m =
                  input.readMessage(
                      com.v2ray.core.app.router.routercommon.CIDR.parser(),
                      extensionRegistry);
              if (cidrBuilder_ == null) {
                ensureCidrIsMutable();
                cidr_.add(m);
              } else {
                cidrBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              inverseMatch_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              resourceHash_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 544002: {
              filePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 544002
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 1;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      countryCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      countryCode_ = getDefaultInstance().getCountryCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 1;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      countryCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.v2ray.core.app.router.routercommon.CIDR> cidr_ =
      java.util.Collections.emptyList();
    private void ensureCidrIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        cidr_ = new java.util.ArrayList<com.v2ray.core.app.router.routercommon.CIDR>(cidr_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.CIDR, com.v2ray.core.app.router.routercommon.CIDR.Builder, com.v2ray.core.app.router.routercommon.CIDROrBuilder> cidrBuilder_;

    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.CIDR> getCidrList() {
      if (cidrBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cidr_);
      } else {
        return cidrBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public int getCidrCount() {
      if (cidrBuilder_ == null) {
        return cidr_.size();
      } else {
        return cidrBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public com.v2ray.core.app.router.routercommon.CIDR getCidr(int index) {
      if (cidrBuilder_ == null) {
        return cidr_.get(index);
      } else {
        return cidrBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder setCidr(
        int index, com.v2ray.core.app.router.routercommon.CIDR value) {
      if (cidrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCidrIsMutable();
        cidr_.set(index, value);
        onChanged();
      } else {
        cidrBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder setCidr(
        int index, com.v2ray.core.app.router.routercommon.CIDR.Builder builderForValue) {
      if (cidrBuilder_ == null) {
        ensureCidrIsMutable();
        cidr_.set(index, builderForValue.build());
        onChanged();
      } else {
        cidrBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder addCidr(com.v2ray.core.app.router.routercommon.CIDR value) {
      if (cidrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCidrIsMutable();
        cidr_.add(value);
        onChanged();
      } else {
        cidrBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder addCidr(
        int index, com.v2ray.core.app.router.routercommon.CIDR value) {
      if (cidrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCidrIsMutable();
        cidr_.add(index, value);
        onChanged();
      } else {
        cidrBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder addCidr(
        com.v2ray.core.app.router.routercommon.CIDR.Builder builderForValue) {
      if (cidrBuilder_ == null) {
        ensureCidrIsMutable();
        cidr_.add(builderForValue.build());
        onChanged();
      } else {
        cidrBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder addCidr(
        int index, com.v2ray.core.app.router.routercommon.CIDR.Builder builderForValue) {
      if (cidrBuilder_ == null) {
        ensureCidrIsMutable();
        cidr_.add(index, builderForValue.build());
        onChanged();
      } else {
        cidrBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder addAllCidr(
        java.lang.Iterable<? extends com.v2ray.core.app.router.routercommon.CIDR> values) {
      if (cidrBuilder_ == null) {
        ensureCidrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cidr_);
        onChanged();
      } else {
        cidrBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder clearCidr() {
      if (cidrBuilder_ == null) {
        cidr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        cidrBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public Builder removeCidr(int index) {
      if (cidrBuilder_ == null) {
        ensureCidrIsMutable();
        cidr_.remove(index);
        onChanged();
      } else {
        cidrBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public com.v2ray.core.app.router.routercommon.CIDR.Builder getCidrBuilder(
        int index) {
      return getCidrFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public com.v2ray.core.app.router.routercommon.CIDROrBuilder getCidrOrBuilder(
        int index) {
      if (cidrBuilder_ == null) {
        return cidr_.get(index);  } else {
        return cidrBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public java.util.List<? extends com.v2ray.core.app.router.routercommon.CIDROrBuilder> 
         getCidrOrBuilderList() {
      if (cidrBuilder_ != null) {
        return cidrBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cidr_);
      }
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public com.v2ray.core.app.router.routercommon.CIDR.Builder addCidrBuilder() {
      return getCidrFieldBuilder().addBuilder(
          com.v2ray.core.app.router.routercommon.CIDR.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public com.v2ray.core.app.router.routercommon.CIDR.Builder addCidrBuilder(
        int index) {
      return getCidrFieldBuilder().addBuilder(
          index, com.v2ray.core.app.router.routercommon.CIDR.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 2;</code>
     */
    public java.util.List<com.v2ray.core.app.router.routercommon.CIDR.Builder> 
         getCidrBuilderList() {
      return getCidrFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.app.router.routercommon.CIDR, com.v2ray.core.app.router.routercommon.CIDR.Builder, com.v2ray.core.app.router.routercommon.CIDROrBuilder> 
        getCidrFieldBuilder() {
      if (cidrBuilder_ == null) {
        cidrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.v2ray.core.app.router.routercommon.CIDR, com.v2ray.core.app.router.routercommon.CIDR.Builder, com.v2ray.core.app.router.routercommon.CIDROrBuilder>(
                cidr_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        cidr_ = null;
      }
      return cidrBuilder_;
    }

    private boolean inverseMatch_ ;
    /**
     * <code>bool inverse_match = 3;</code>
     * @return The inverseMatch.
     */
    @java.lang.Override
    public boolean getInverseMatch() {
      return inverseMatch_;
    }
    /**
     * <code>bool inverse_match = 3;</code>
     * @param value The inverseMatch to set.
     * @return This builder for chaining.
     */
    public Builder setInverseMatch(boolean value) {
      
      inverseMatch_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool inverse_match = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInverseMatch() {
      bitField0_ = (bitField0_ & ~0x00000004);
      inverseMatch_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString resourceHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * resource_hash instruct simplified config converter to load domain from geo file.
     * </pre>
     *
     * <code>bytes resource_hash = 4;</code>
     * @return The resourceHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResourceHash() {
      return resourceHash_;
    }
    /**
     * <pre>
     * resource_hash instruct simplified config converter to load domain from geo file.
     * </pre>
     *
     * <code>bytes resource_hash = 4;</code>
     * @param value The resourceHash to set.
     * @return This builder for chaining.
     */
    public Builder setResourceHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      resourceHash_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * resource_hash instruct simplified config converter to load domain from geo file.
     * </pre>
     *
     * <code>bytes resource_hash = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceHash() {
      bitField0_ = (bitField0_ & ~0x00000008);
      resourceHash_ = getDefaultInstance().getResourceHash();
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 5;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 5;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 5;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string code = 5;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object filePath_ = "";
    /**
     * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return The filePath.
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return The bytes for filePath.
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @param value The filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filePath_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePath() {
      filePath_ = getDefaultInstance().getFilePath();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
     * @param value The bytes for filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filePath_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.routercommon.GeoIP)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.router.routercommon.GeoIP)
  private static final com.v2ray.core.app.router.routercommon.GeoIP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.router.routercommon.GeoIP();
  }

  public static com.v2ray.core.app.router.routercommon.GeoIP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoIP>
      PARSER = new com.google.protobuf.AbstractParser<GeoIP>() {
    @java.lang.Override
    public GeoIP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GeoIP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoIP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.router.routercommon.GeoIP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

