// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface GeoSiteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.GeoSite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
   */
  java.util.List<com.v2ray.core.app.router.routercommon.Domain> 
      getDomainList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
   */
  com.v2ray.core.app.router.routercommon.Domain getDomain(int index);
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
   */
  int getDomainCount();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
   */
  java.util.List<? extends com.v2ray.core.app.router.routercommon.DomainOrBuilder> 
      getDomainOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
   */
  com.v2ray.core.app.router.routercommon.DomainOrBuilder getDomainOrBuilder(
      int index);

  /**
   * <pre>
   * resource_hash instruct simplified config converter to load domain from geo file.
   * </pre>
   *
   * <code>bytes resource_hash = 3;</code>
   * @return The resourceHash.
   */
  com.google.protobuf.ByteString getResourceHash();

  /**
   * <code>string code = 4;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 4;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string file_path = 68000 [(.v2ray.core.common.protoext.field_opt) = { ... }</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
