// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dat.proto

package com.v2ray.core.app.router.routercommon;

public interface GeoSiteListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.router.routercommon.GeoSiteList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoSite entry = 1;</code>
   */
  java.util.List<com.v2ray.core.app.router.routercommon.GeoSite> 
      getEntryList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoSite entry = 1;</code>
   */
  com.v2ray.core.app.router.routercommon.GeoSite getEntry(int index);
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoSite entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoSite entry = 1;</code>
   */
  java.util.List<? extends com.v2ray.core.app.router.routercommon.GeoSiteOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.router.routercommon.GeoSite entry = 1;</code>
   */
  com.v2ray.core.app.router.routercommon.GeoSiteOrBuilder getEntryOrBuilder(
      int index);
}
